### ISSUE TITLE
How to switch between Proton versions ?

### ISSUE THREAD

**Issue by rshamsnejad** [rockerbacon/modorganizer2-linux-installer#102]
Hi !

First of all, thanks for the script. It runs perfectly :ok_hand: Currently running SkyUI + OpenCities + Immersive College of Winterhold. I'm loving it.

But...

I originally installed the game as well as the Lutris script with the official Proton 5.0-9, but I'm experiencing some FPS drops that are a bit annoying. It's largely playable, but annoying. So I wanted to try a Glorious Eggroll build, since some ProtonDB reports seem to indicate that performance is better with it. 

I see that in `proton-launch.sh`, one can use the `--customver` flag to use a custom Proton version. So I edited that in `run.sh`, switched Skyrim to use GE in Steam, launched the game once, and tried to use MO.

Oh boy did it go bad. :smile:  I can't remember all the issues, but I then backpedaled and switched everything back to the official Proton. But then, when I launched the game, sound was missing and mouse movement wasn't working anymore. I figured the Proton install was totally borked, so I deleted the corresponding `pfx` folder, reinstalled MO using the "Update" instructions in the README, reinstalled the mods, and it reset my modded Skyrim back to normal. Phew !

That leads me to my question : what would be the correct steps if I wanted to switch between Proton versions to find the right one ?

**Comment by rockerbacon** [comment]
During testing, it was found that Valve's Proton 5.0 contains the only version of Wine that can properly run the latest version of MO2. You might have some luck with older versions (2.2.0 or older), check the releases [here](https://github.com/ModOrganizer2/modorganizer/releases).

Always make sure the game is configured in Steam to use the same version of Proton as the one specified with the `--customver` option.

**Comment by rshamsnejad** [comment]
Thanks for the answer.

If I understand correctly, Proton version X is based on Wine version X, so I assume that it goes the same for the GE fork, ie. Proton-GE version X is also based on Wine version X. So if I try for example Proton-5.8-GE-2-MF, it should be a recent enough version of Wine to run MO, right ?

So do these steps sound right to you if I wanted to try ?

1. Switch Skyrim to Proton-5.8-GE-2-MF in Steam
2. Launch the game once in Steam
3. Edit `run.sh` to specify `--customver Proton-5.8-GE-2-MF` in place of the `--protonver` flag
4. Launch MO through Lutris

**Comment by rockerbacon** [comment]
> If I understand correctly, Proton version X is based on Wine version X, so I assume that it goes the same for the GE fork, ie. Proton-GE version X is also based on Wine version X. So if I try for example Proton-5.8-GE-2-MF, it should be a recent enough version of Wine to run MO, right ?

That's not exactly how things go. Valve makes their own tweaks to Wine and it's difficulty to affirm that "if it works in version x it also works in version x.y" without carefully looking at both versions.

> 1. Switch Skyrim to Proton-5.8-GE-2-MF in Steam
> 2. Launch the game once in Steam
> 3. Edit `run.sh` to specify `--customver Proton-5.8-GE-2-MF` in place of the `--protonver` flag
> 4. Launch MO through Lutris

Add a step before all that and you're good to go:

0. Delete the existing prefix in `path/to/steam/library/steamapps/compatdata/<game_appid>`. Check [here](https://github.com/rockerbacon/lutris-skyrimse-installers/tree/master/gamesinfo) for the appid.

**Comment by rshamsnejad** [comment]
Okay so I tried it with Proton-5.8-GE-2-MF, and got a runtime error after the first few steps of MO.

Started over with Proton-5.11-GE-2-MF : MO runs fine, I had to do the config all over again (Nexus API key + import all mods). Then Skyrim launches, but when I try to load my save, the game says that the mod files are missing, despite them being correctly checked in MO. This is weird isn't it ? Aren't the mods stored in the game's directory ?

Since I backed up the prefix instead of deleting it on the first step, I could quickly go back to my working setup with official Proton. I'll investigate this and give it another shot tomorrow. Thanks

**Comment by 7hr08ik** [comment]
Im having the same problem, only recently realised that, even though the game was setup is steam to us GE, it was actually running Proton 5.0 steam.
Found this thread when i got the same issue. The game boots up from GE-Proton, i can see my save files. But the game no longer see's any of the mods i have installed.

**Comment by rockerbacon** [comment]
I'm marking this as a discussion so people will have a centralized place to discuss their trials and errors but custom Proton and Wine versions are not officially supported.

This problem seems to be related to Valve's Proton 5 containing the only version of Wine with proper support for some of the Visual C++ 2019 features used by MO2, which would explain why versions of MO2 running VC++ 2017 (2.2.0 and older) work better with other versions of Wine/Proton.

This conversation would be a lot more productive if taken to [GloriousEggroll himself](https://github.com/GloriousEggroll/proton-ge-custom) but it seems the project doesn't accept issue reports.

**Comment by freddfx** [comment]
> Okay so I tried it with Proton-5.8-GE-2-MF, and got a runtime error after the first few steps of MO.
> 
> Started over with Proton-5.11-GE-2-MF : MO runs fine, I had to do the config all over again (Nexus API key + import all mods). Then Skyrim launches, but when I try to load my save, the game says that the mod files are missing, despite them being correctly checked in MO. This is weird isn't it ? Aren't the mods stored in the game's directory ?
> 
> Since I backed up the prefix instead of deleting it on the first step, I could quickly go back to my working setup with official Proton. I'll investigate this and give it another shot tomorrow. Thanks

I've had this same exact issue, it seemed to be related to MO2's virtual file system not working properly with proton-GE (tested with 5.9 and 5.11)

**Comment by 7hr08ik** [comment]
From what i have managed to gather from bits and pieces in different forums......The WINE stable branch uses a different base than WINE staging. Proton is built from wine staging, and therefore will not work.

I did play around with building GE's wine-custom. But i'm dumb and lazy. After the first day, i just gave up. For me, using WINE stable, and adding faudio to my lutris container helped a lot

**Comment by katawful** [comment]
Proton-tkg doesn't work (which I need in order to add a patch to fix a problem), but it also builds from staging. Would building from stable work? I don't particularly care about the staging patches, I just don't want to waste an hour building for nothing

**Comment by rockerbacon** [comment]
> Proton-tkg doesn't work (which I need in order to add a patch to fix a problem), but it also builds from staging. Would building from stable work? I don't particularly care about the staging patches, I just don't want to waste an hour building for nothing

If you really really need this then my recommendation is downgrading to [MO2 2.2.0](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.2.0) and using `vcrun2017` instead of `vcrun2019`. No guarantees it will work but as [stated before](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/102#issuecomment-653917622), this older version has better compatibility with different Wine builds.

**Comment by ajventer** [comment]
> > Proton-tkg doesn't work (which I need in order to add a patch to fix a problem), but it also builds from staging. Would building from stable work? I don't particularly care about the staging patches, I just don't want to waste an hour building for nothing
> 
> If you really really need this then my recommendation is downgrading to [MO2 2.2.0](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.2.0) and using `vcrun2017` instead of `vcrun2019`. No guarantees it will work but as [stated before](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/102#issuecomment-653917622), this older version has better compatibility with different Wine builds.

I tested this, the older version starts up but the VFS doesn't work - as the game loads SKSE doesn't load any plugins. I use the optimised vanilla textures and I moved the originals to a backup folder, and it's instantly obvious the VFS didn't work as even on the load screen the textures are missing.

This is a pity because for me the only way to get SKSE64 and ENB to work is using proton-GE.

**Comment by rockerbacon** [comment]
For anyone who may still be following this issue: pre-release [4.0.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.0.0) should be compatible with more Proton versions.

Just keep in mind:
- MO2 also needs to be updated since newer versions include necessary changes to USVFS
- You may need to rename a directory if updating from a older version. Read the master's readme for instructions
- The newer version no longer installs through Lutris
- This is a pre-release and hasn't been extensively tested. If you already have a working experience, make sure to backup before updating
