### ISSUE TITLE
xEdit Drag and Dropping Only Works in a WinXP Prefix

### ISSUE THREAD

**Issue by ThisNekoGuy** [rockerbacon/modorganizer2-linux-installer#136]
Dragging and Dropping only works when the compatibility mode is set to Windows XP, which is important for conflict resolution, but I would imagine that setting it to WinXP would be problematic for running FO4 itself.

Aside from that. only the 32-bit xEdit runs in MO2, the 64-bit one doesn't launch.

**Comment by Baguettedood** [comment]
Was quite confused when encountering this with SSEEdit. If nothing else, you can set individual programs to run as if they were in a Windows XP prefix by opening winecfg and pressing "Add application..." in the Applications tab, finding the appropriate exe and making the adjustments. This could made a decent addition to the install script, since it's pretty much just a registry entry once it's set.
