### ISSUE TITLE
Proton

### ISSUE THREAD

**Issue by mthsgrc** [rockerbacon/modorganizer2-linux-installer#196]
I'm running Wine Skyrim. 
When I tried running the MO I got Could not find Proton version matching '5.*'

Any workaround?

**Comment by Blacksmoke16** [comment]
@mthsgrc There seems to be an incompatibility with the current version of proton that I had installed (5.13.x).  When starting it I was getting:

> lutris could not find proton

What I did to fix this was set steam and morrowind to use Proton 5.0.x version.  Then start morrowind so that it'll install that version of Proton if it's not already.  I then had to delete `Proton 5.13` from `steamapps/common` as lutris was finding that instead of the 5.0 version.  After that I was able to get it to at least get it to launch.  I also had to disable some fomod_csharp.dll plugin to get things to actually show the UI.

Disclaimer:  I just started using this installer today, I'm sure someone more familiar with things may have some thoughts as well.

**Comment by mthsgrc** [comment]
@Blacksmoke16 I'm not using Steam, though it seems to request that.
I'll try what you suggested.
Thanks for your time

**Comment by mthsgrc** [comment]
It didn't work with the tip @Blacksmoke16 gave above. I tried installing the proton 5.0 but the same error happened.
I'll stick with the first version of MO for now, even though it is not optimal.

**Comment by rockerbacon** [comment]
Closing since the installer no longer runs a proton search.
