### ISSUE TITLE
MO2 doesn't download any mod?

### ISSUE THREAD

**Issue by akechichi** [rockerbacon/modorganizer2-linux-installer#305]
so, MO2 doesn't download any mod, when i try to use the "download with manager" feature in nexus, it asks to choose an app, I choose MO2, and then a error message appears saying "download failed" , and when i try to download something manually,  the .7z file just doesn't appear as an option to open, MO2 acts as if my download folder is empty.
my skyrim SE opens fine, and everything else seems alright, i had skse and one mod installed before installing mo2, but since mo2 recognizes that mod i'm not sure if that's the problem
any ideas on how to solve?

**Comment by zara1193** [comment]
It's likely related, but I've noticed some screwiness going on with my setup as well. Despite selecting the NXM handler as the default program to open NXM links in Firefox, absolutely nothing happens when I click them. Everything else about MO2 functions completely as expected, though.

I suspect it's related, but I run both Firefox and Steam through Flatpak. Perhaps the handler script needs to be tweaked to reflect that?

**Comment by InsaneJ** [comment]
After installation downloading via "Mod Manager Download" button in Firefox worked as expected. Then after closing and starting MO2 it no longer works.

In the MO2 settings menu under the Nexus tab there's an option Associate with "Download with manager" links. This button does not fix the issue for me.

I'm running Manjaro with the default installation options for Steam and Firefox, no Flatpack.

**Comment by NicScrutAlv** [comment]
Also having trouble with this — running on SteamOS 3, MO2 doesn’t recognise manually downloaded files in my downloads folder, and downloading directly from Nexus doesn’t do anything (no error messages, just blank). Tried using both Google Chrome (MO2 application can’t be selected) and Firefox (selecting MO2 or Nxm handler doesn’t initialise any download)

**Comment by TermGrecos** [comment]
Same issue with the download with manager. However, while it does not work when the manager is open, when the manager is closed it starts up the mod manager and downloads perfectly fine. I am on Linux Mint latest version. The game is Skyrim (original). It did connect fine to nexus.

**Comment by sizzlemac** [comment]
Yeah I'm having the same issue with Firefox keeps asking me what I want to associate nxm files with no matter what I do with nxmhandle.exe (deleting the nxmhandle.ini file and redoing the process), or trying to associate MO2 with NXM files. It's connected to the Nexus. The file types according to me checking the $PATH is what they're supposed to be, and according to everything but Firefox, MO2 is supposed to be handling NXM files when I push download...yet it then asks me what program to associate NXM files with when I push it.

I went into the Application settings in Firefox and changed it to associate NXM files with MO2. When I exit, and return it acts like I did nothing. I tested it by switching a different option and redoing that option, exited Firefox, and opened it up checking the setting, and the other thing saved to what it was changed to, but in Applications, NXM is still set to the default "Ask what to associate this file with" as if nothing happened.

I can't figure out what's going on. It's gotta be something with Firefox cause I've never had this problem with any other browser, but I'm not going to completely switch browsers just because of just one thing. Nothing about it seems to make any sense to me at all and I'm not finding any fixes anywhere I search except for stuff from 2015 or 2018 that is no longer relevant.

**Comment by Cassityblanca** [comment]
Exact same scenario as TermGrecos for me, and 3 others I've spoken to. Vortex is more or less useless for us while this issue exists.

**Comment by lilithwhite** [comment]
I'm getting the exact same behavior on Manjaro that I just installed. I was using Pop OS earlier where it worked just fine but I needed a newer version of Mesa for my new GPU. I guess I can download mods by booting into the old OS drive or just download mods one by one by closing mod organizer after every one but it's quite an annoying bug.

**Comment by rockerbacon** [comment]
Refer to #317
