### ISSUE TITLE
Installer tries and fails to create directory under /tmp in Ubuntu 22.04

### ISSUE THREAD

**Issue by Zackey** [rockerbacon/modorganizer2-linux-installer#335]
Installer cannot create its directory under /tmp. This may be caused by exiting early although in my case I think it was just no permissions. 

Steps to reproduce: 
Have ubuntu 22.04 
Run script
???
Error?

mkdir: cannot create directory ‘/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07’: Permission denied

After checking the google, it seems root user is owner of /tmp on ubuntu 22.04 and that the regular user (which you must run script as) can't create directory. Note that if you run script as root, it will be unable to locate steam correctly as script relies on home path for this. 

Suggested fix is just to change the script to make a directory in home directory, such as ~/tmp/mo2-folder-here

I fixed it myself by setting 777 on /tmp using chmod, then just set it back after the script was finished.

**Comment by picobyte** [comment]
Could be the user running the script can't write to /tmp (try touching a (new) file in /tmp), or a parent directory was not created in the script; a mkdir should be a 'mkdir -p' or maybe you're just out of disk space on /tmp?

**Comment by rockerbacon** [comment]
Permission settings for `/tmp` should be 1777. Ubuntu likely didn't set `/tmp` to something other than that, this would break most programs creating temporary files. The [FHS specifies](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html):
```
The /tmp directory must be made available for programs that require temporary files.
```
I'd assume limiting access solely to programs owned by root breaks this specification.

Something like `~/tmp` shouldn't be used because `/tmp` is a proper temporary mount, and creating such a mount requires root permissions.
