### ISSUE TITLE
SteamOS/Fallout New Vegas - "An instance of Mod Organizer is already running"

### ISSUE THREAD

**Issue by pippaine** [rockerbacon/modorganizer2-linux-installer#376]
1. Install modorganizer2-linux-installer, following all instructions
2. Select "New Vegas" (4GB patched) and hit "Run"
3. Instead of running the game, a new instance of MO2 is launched and the message "An instance of Mod Organizer is already running" is displayed

**Comment by misterkeevs** [comment]
Same issue here. Tried different versions of Proton, changing game directory (SD card and internal) with no success

**Comment by cprin21** [comment]
This. Feels like a symlink problem where because the way this works is symlinking the launcher of the game into launching MO2 in the game's environment instead, for some reason it's also symlinking the base game itself or xnvse into MO2 and thus you get a message that MO2 is already running instead of launching the game.

**Comment by pippaine** [comment]
I managed to get my instance working. Try these steps as a workaround:

1. Delete the folder <steamapps>/compatdata/22380/
2. Set proton version to 7.0-4 instead of 6.3-8
3. Launch New Vegas normally through steam (clean vanilla install, or at least with the original FalloutNVLauncher.exe). Optionally set graphics settings to Ultra now
4. Close the launcher and install modorganizer2-linux-installer, ignoring only the instruction about using proton version 6.3
