### ISSUE TITLE
How to manually set game path

### ISSUE THREAD

**Issue by VladislavNekto** [rockerbacon/modorganizer2-linux-installer#378]
```
mv: cannot stat '/home/orange/.steam/debian-installation/steamapps/common/Fallout 4/Fallout4Launcher.exe': No such file or directory
```
It's just in different place. How to set my path to game?

**Comment by VladislavNekto** [comment]
It's bug in util that finds path, obviously

**Comment by VladislavNekto** [comment]
```
INFO: found Steam in '/home/orange/.steam/debian-installation'
/home/orange/.steam/debian-installation
/home/orange/.storage0/Games/SteamLibrary
/home/orange/.storage2/SteamLibrary
/home/orange/.storage1/SteamLibrary
/srv/SteamLibrary
/mnt/sdd/SteamLibrary
INFO: steam not found in '/home/orange/.var/app/com.valvesoftware.Steam/.local/share/Steam'
```
Game stored in /srv/, but script think in my home, but it's wrong

**Comment by Ratione** [comment]
I got around this by changing what string the installer was looking for in the "step/select_game.sh" file. Not a great solution, but it *did* work.

**Comment by Hobby-boy** [comment]
I've had this issue with Skyrim on my Steam Deck when running the installer, which was installed on the microsd instead of the internal storage.
I was able to get the installer to write the files into the correct game directory by creating a symbolic link from the directory on my microsd card to the default steamapps directory.

The commands I used were:
```
cd /home/deck/.local/share/Steam/steamapps/common
ln -s '/run/media/mmcblk0p1/steamapps/common/Skyrim Special Edition' 'Skyrim Special Edition'
```
