### ISSUE TITLE
"An Instance of Mod Organizer is already running" for Fallout New Vegas mod organizer 

### ISSUE THREAD

**Issue by intheworlditsgone** [rockerbacon/modorganizer2-linux-installer#387]
How do I fix this? I havent seen any REAL viable solutions to solve this issue, and its been neglected by the devs. Is there anyway around this?

**Comment by patrioticparadox** [comment]
You'll need to provide more information about your issue to get any meaningful replies

**Comment by AJRed** [comment]
I'm having the same problem as OP. It seems that the FalloutNV.exe binary opens mod organizer. nvse_loader.exe also does the same.  I think the only change I made to the binary after installing MO2 was run the 4GB patcher. Let me know if I need to provide more information

**Comment by coffandro** [comment]
im having the same issue on my TTW install

**Comment by kenny-patrick** [comment]
I was having the same issue on TTW as well. I fixed this by copying FalloutNVLauncher.exe into the game folder from my Windows PC with a working  TTW install. The trick is, I renamed the exe from PC. If you overwrite the exe on the Linux device, MO2 won't open when you launch the game from Steam. Inside of MO2, I changed the entry for the Launcher to use the exe I copied from my PC. That way, MO2 will still run but the game launches just fine.

**Comment by MrRollton** [comment]
To anyone facing this problem: for me it it happened because the GPU name stated in falloutprefs.ini differed from the one I used at the time (I have a dual-GPU laptop and the first time I started the game I used the dedicated GPU, but later switched to integral). Here's what worked for me:
* edit the "Fallout Launcher" executable in MO2 menu to include the underscore in the "Binary" path (for example, if the default path is
`Z:\path-to-steam-lib\steamapps\common\Fallout New Vegas\FalloutLauncher.exe`
you should change it to
`Z:\path-to-steam-lib\steamapps\common\Fallout New Vegas\_FalloutLauncher.exe`
* select the Fallout Launcher from the drop-down executable menu
* "Run" it. You should see the launcher and two pop-up messages about setting the game to appropriate settings level
* you can close the launcher after messages disappear
* after that, select New Vegas from the same dropdown and it should work

**Comment by rockerbacon** [comment]
Just to give more clarity, users just need to follow the [post-install instructions](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md) and setup MO2 to launch the original game launcher.

**Comment by zbikk** [comment]
> Just to give more clarity, users just need to follow the [post-install instructions](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md) and setup MO2 to launch the original game launcher.

launching the game through the launcher throws an application load error #588 related probably and the new vegas entry just tries to launch another instance of mo2

**Comment by rockerbacon** [comment]
Did a little bit of investigating and the issue is that `FalloutNV.exe` will execute `FalloutNVLauncher.exe`  whenever it detects that `falloutprefs.ini` needs to be created/updated.

It may be possible to workaround the issue by modifying the redirector ([steam-redirector/main.c](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/steam-redirector/main.c)). If it is executed without any arguments:
1. Detect whether MO2 is already running
2. Launch the original game launcher if it is
3. Launch MO2 as usual, otherwise
