### ISSUE TITLE
New Vegas (xNVSE) Loop

### ISSUE THREAD

**Issue by SentaiBrad** [rockerbacon/modorganizer2-linux-installer#412]
When I launch MO2 from steam on my Deck, and then launch the TTW exe (New Vegas exe), xNVSE's default behavior is to autoload xNVSE and launch the game. However, because the script changes the game from steam, it's stuck in a loop. So play game -> mo2 launch game -> mo2 tries to launch mo2. 

Is there any fix I can do, or does the script need to be changed / an option made for New Vegas?

**Comment by Zouizoui78** [comment]
What executable are you launching inside mo2 ? It seems to me that you're telling mo2 to launch the game, new_vegas.exe (or whatever it's called, I don't own the game) instead of the script extender (nvse.exe or something like that).
The former would indeed cause a loop since the game executable is replaced by the redirector which opens mo2.

**Comment by cprin21** [comment]
Uninstall the game, remove all traces that you installed modorganizer2-linux-installer via removing the New Vegas folder from ~/.local/share/Steam/steamapps/common/, and the folder the install script made in ~/Games. Then go to your compatdata folder and remove the one pertaining to New Vegas' Steam ID (22380).
Try the installation process again. That worked for me personally.

**Comment by Razatop** [comment]
Sentai did you ever get a fix for yourself?
