### ISSUE TITLE
Feature Request: UI Convenience

### ISSUE THREAD

**Issue by cprin21** [rockerbacon/modorganizer2-linux-installer#415]
The console window that opens when the launcher is clicked seems to make alt tabbing kind of annoying. An option to remove the console window would be greatly appreciated.
Secondly, I was hoping there was a way to put "moshortcut://SkyrimSE:SKSE" into the launch arguments area for SkyrimSE and for other Bethesda games as well. Said console comes up with an error with that as a launch argument.

Essentially just like you can do on Windows, I'd like to be able to click launch on Steam, and the game would come up after a short 'loading vfs' message, fully modded without the MO2 window or the console window coming up.
I would like to know how to do this myself via some info on the github page if at all possible.

**Comment by Zouizoui78** [comment]
I have opened two PRs to do exactly what you want.

[To hide the console window](https://github.com/rockerbacon/modorganizer2-linux-installer/pull/413) you just have to add the `-mwindows` option to the redirector compilation. Keep in mind that just like on Windows the small window telling that "Mod Organizer is waiting for the application to close before exiting" will still show up so I'm not sure if it will fix your alt-tabbing issue.

[Forward the steam launch option to MO2](https://github.com/rockerbacon/modorganizer2-linux-installer/pull/411) requires a bit more work but it can easily be done too. You can read [this issue](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/401) to get some explanation.

Backup your existing redirector before doing this just in case.

**Comment by cprin21** [comment]
Great work but at the same time I'm a little lost - I don't have experience with this script in general and so I don't really know what it means to add an option to the redirector compilation. I added the two files (one from each of your forked projects as you've changed one each) to the mod organizer 2 installation folder under the steam-redirector subfolder but from there I'm lost running install.sh produces the same results as this original project, which means successful but no difference.

The way I use this script is to drag and drop the master branch onto 4.3.0 and replace all. Unsure if there's a proper way to do this, since install.sh from the master branch without pasting on top of 4.3.0 does not install successfully.

**Comment by Zouizoui78** [comment]
You don't have to re-run the whole installer, I only touched the redirector (the program launched by Steam that launches MO2 instead of the game, hence the _redirection_).

To keep things simple you can clone [this branch](https://github.com/Zouizoui78/modorganizer2-linux-installer/tree/both_changes) to get both changes (launch option and console hiding).

Now the redirector is ready to be compiled. According to the error you encounter you lack a depency, specifically the mingw's pthread implementation. I don't know what distro you're using but on Arch (the distro I'm using) it's the package called `mingw-w64-winpthreads`. If you're on Arch just install the group `mingw-w64` and you'll get the whole mingw installation.

Once you have that installed you should be able to compile the redirector just by calling `make` in the `steam-redirector` directory. It will produce a `main.exe` file that you can rename to `SkyrimSELauncher.exe` and place into your Skyrim's installation directory (`/path/to/SteamLibrary/steamapps/common/Skyrim Special Edition`).

If everything went without issue you should be able to launch the game via Steam without seeing a console window opening and with a launch option telling MO2 what to do.

**Comment by cprin21** [comment]
The package in Fedora 36, the distro I use these days is called mingw64-winpthreads, and I have that installed and yet get the same error where it can't seem to find -lpthread.

**Comment by Zouizoui78** [comment]
It might be a problem with static/dynamic linking.

According to [this page](https://packages.fedoraproject.org/pkgs/mingw-winpthreads/), on Fedora the static and dynamic versions on mingw's pthread library are split in different packages. The compilation of the redirector seems to be using static linking with the `-Bstatic` option, but since you have `mingw64-winpthreads` installed your system only has the dynamic library.

Install `mingw64-winpthreads-static` and try again.

**Comment by cprin21** [comment]
> It might be a problem with static/dynamic linking.
> 
> Install `mingw64-winpthreads-static` and try again.

Instantaneous success!
