### ISSUE TITLE
Skyrim SE installation installations no longer function (old version of SKSE)

### ISSUE THREAD

**Issue by Infinoid** [rockerbacon/modorganizer2-linux-installer#441]
I followed the installation instructions for Skyrim Special Edition, and was able to install and launch modorganizer2.  However, when I select the SKSE tool in MO2 and click Run, it fails.  The SKSE64 loader opens a popup window saying that the game version did not match what SKSE64 expects, and refuses to run.

![image](https://user-images.githubusercontent.com/50254/212488978-7ad9747c-fcfb-4dbb-8c7b-e96cce10d788.png)

The popup says the game version (Runtime) is 1.6.640 and the SKSE64 version was 2.1.5.  The correct version of SKSE64 should be 2.2.3.

I updated the installed version of SKSE to 2.2.3 by hand, and now it works.

Your installation instructions clearly say:

```
2. Download the the latest stable release [here];
```

and I did so, but the latest stable release no longer works.  I saw that [the game data file](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/gamesinfo/skyrimspecialedition.sh#L6) has been updated to include the correct version of SKSE, but these updates have not yet made it into a release.

A new release is needed.

For what it's worth, I have not purchased the "Anniversary Edition" of Skyrim, searching my steam library only shows Skyrim and Skyrim SE.  I am using a fresh installation of Skyrim SE installed via steam, and this is the version I got.

(Apart from this, `modorganizer2-linux-installer` is very useful to me.  Thanks!)

**Comment by Zellogie** [comment]
Had this issue too. Did a manual install of SKSE and then it worked just fine. Had an issue with something right after, think it said something was missing, can't remember if it was the launcher or other exe. So did an update/installer again and it was working as intended.

**Comment by kleshas** [comment]
I'm working on a possibly related issue.  Reinstalled steam, Skyrim, and MO2 via this installer.  Updated the skyrimspecialedition.sh in \gameinfo as mentioned above.  

Now, however, MO2 doesn't want to run skyrim.  Nothing happens at all when running via skse. SkyrimSELauncher.exe is running, but no display, and no errors or relevant logs.  Ran Skyrim before installing MO2, set proton to 6.3, reinstalled skyrim and checked files in steam.

After resetting skyrim files dxsetup runs but that window always disappears at step 1.  dxsetup runs every time.  Game doesn't launch after clicking in Play in the launcher window.

When trying to run Skyrim Special Edition from MO2, it says steam isn't running.

**Comment by DominicWatson** [comment]
I just came here trying to fix this issue in the project code, only to find that the issues appear to have already been fixed.

However, there has been no release tag made since last January and the README points to that tag. I think all the issues I had with out of date SKSE and missing FNIS directory would have been fixed if I'd downloaded the `master` branch.

I'm going to do a clean reinstall and try that and will report back.

**Comment by nickonegen** [comment]
Same issue here on a clean Skyrim install! (BUMP)

Re-installing SKSE myself somehow made the game "not respond" right after the game launched (I probably messed up somewhere 😅), fortunately removing the SKSE files and then re-installing MO2 from `master` did the trick and it works like a charm. 🙌

<hr />

**For any readers needing help:**

Clone this repo or just [download it as a .zip](https://github.com/rockerbacon/modorganizer2-linux-installer/archive/refs/heads/master.zip).

Running `./install.sh` is probably gonna error out immediately due to missing redirector - which you're gonna have to build yourself:

```sh
cd steam-redirector
make
```

Doesn't work? 👉 [build requirements](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/steam-redirector#requirements)

```sh
cd ..
./install.sh
```

**Comment by rockerbacon** [comment]
Yesterday's release includes an updated SKSE64
