### ISSUE TITLE
Steam doesn't open MO2, just opens skyrim directly

### ISSUE THREAD

**Issue by kbhors** [rockerbacon/modorganizer2-linux-installer#478]
OK so:

Installed skyrim, got it running, fixed the infamous no speech/music problem. Installed MO2 with the script. Steam was launching MO2 as expected.

Then I made the foolish mistake of pasting my backed up MO2 and Skyrim folders from my old windows install.

Now steam doesn't launch MO2, it just launches the game. Attempting to run the install script, that offers to update MO2 then fails to do so, with "check the terminal for details" in the dialog box. There's nothing in the terminal related at all.

`INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrim_skse_1_07_03.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrim_skse_1_07_03'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'`

I can open a file browser and launch MO2 in skyrim's proton instance, but if I try to launch skyrim from MO2 now it just complains steam isn't running.

How do I fix it so that steam opens MO2 again?

**Comment by lunasoldev** [comment]
have you found a fix for this issue?

**Comment by kbhors** [comment]
Nope. But it was months ago. The OS was long since wiped and I have a new computer now.

**Comment by rockerbacon** [comment]
When you replaced your folder with your backed up Skyrim folder you undid some of the work from the installer. Specifically, you uninstalled the [Steam redirector](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/steam-redirector) and manually reinstalling it could've worked.

Since you were unable to re-run the installer, there's no guarantee anything would've actually worked without taking a deep dive into exactly what happened when your overwrote the files.
