### ISSUE TITLE
Installer can't find steam

### ISSUE THREAD

**Issue by Zwolf6** [rockerbacon/modorganizer2-linux-installer#525]
I get this error message when trying to install Mo2 for Oblivion: INFO: steam not found in '/root/.var/app/com.valvesoftware.Steam/.local/share/Steam'

**Comment by inyund** [comment]
me too, im trying to install for skyrim se
```
steam not found in '/home/username/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.7.0', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 28, in cli
    main(args)
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 264, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

```

**Comment by inyund** [comment]
> I've had that same issue, however for me it was protontricks that prevented the script from working. See if that same thing doesn't apply to you as well.
> 
> @inyund if you look at line 3 of your output you can see that there's some complaints coming from /usr/bin/protontricks. I'm not sure about those later ones though. I'd guess that you might be missing some dependencies or something. I'm not sure as I don't use Ubuntu.
> 
> Also the message is only an info message, not an error. The installer should be able to continue doing its thing even if that info message pops up I believe.
> 
> And @Zwolf6: It'd be easier to fix the issue if you paste the entire error output so that other people could help you more easily.

im new in linux so i dont really understand whats going on, thanks for pointing that out. after carefully reading the documentation on protontricks i notice that they warned about how some distros such as ubuntu often have outdated packages for protontricks. so i installed the flatpack version as suggested, and now the installer running smoothly.

**Comment by sarcasticDweller** [comment]
Having a similar issue when installing on Steam Deck for FNV.

It's worth noting that I tried an install beforehand, but it failed during the actual install (ie: the game had already been run once without the installer, and was shut down) I didn't run it in a terminal, so I wasn't able to recover the error messages. However, since then, the app crashes when I select my game, and returns the same output to the terminal every time.

``
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
``

**Comment by rockerbacon** [comment]
> I get this error message when trying to install Mo2 for Oblivion: INFO: steam not found in '/root/.var/app/com.valvesoftware.Steam/.local/share/Steam'

It’s trying /root/ which means the script was run as a root user. The script shouldn’t be run as root.

@inyund your issue is completely unrelated. Your problem seems to be that you’re running Protontricks 1.7.0, which is ancient at this point. Note that you don’t have error logs other than the Protontricks ones.

**Comment by rockerbacon** [comment]
@sarcasticDweller the installer logs clearly show both Steam and the game you want to use MO2 on were found at `/home/deck/.local/share/Steam` and you have no error logs regarding not found directories.
