### ISSUE TITLE
This repo is for linux user

### ISSUE THREAD

**Issue by Mobiacikaka** [rockerbacon/modorganizer2-linux-installer#532]
And it needs to be built in Windows! What a joke!

**Comment by rockerbacon** [comment]
I've been maintaining this repo for years and haven't touched a windows machine since 2017.

If you're referring to the .exe steam redirector file, there are specific instructions for compiling it on Arch and Fedora: https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/steam-redirector and a link to where you can find a list of pre-built mingw binaries for other distributions. You're also free to compile mingw, bash, GNU utils, zenity, python, 7z, etc, all from source, which I highly recommend.
