### ISSUE TITLE
Version 2.5

### ISSUE THREAD

**Issue by MartinF99** [rockerbacon/modorganizer2-linux-installer#543]
Mod organizer 2 has recently released version 2.5. Which also adds starfield support. Consider updating the script to version 2.5

**Comment by jimmon89** [comment]
version 2.5 is not currently compatible with wine/proton
see the this report on the mo2 github
[https://github.com/ModOrganizer2/modorganizer/issues/372](https://github.com/ModOrganizer2/modorganizer/issues/372)

**Comment by MartinF99** [comment]
Ah this is in line with my own testing, it does simply not launch

**Comment by Silarn** [comment]
A patch to fix wine has been accepted by the Wine devs, so in theory a bleeding edge build should work.

**Comment by cprin21** [comment]
> in theory a bleeding edge build should work.

Nope,  doesn't work, not on Proton Experimental, not on a TKG Proton Nightly.

**Comment by suamor** [comment]
I have used wine-8.21-staging download for Ubuntu 22.04 LTS and ModOrganizer as well as the latest LOOT work just fine (non-proton wine). I can't check the proton wine tkg on Ubuntu.

**Comment by cprin21** [comment]
> I have used wine-8.21-tkg-staging download for Ubuntu 22.04 LTS and ModOrganizer 2.5.1 as well as the latest LOOT 0.22.3 work just fine (non-proton wine). I can't check the proton wine tkg on Ubuntu.

Would you mind sharing how you accomplished this? wine staging tkg doesn't work by running it as a proton version, which is needed when using this repo's method of installing MO2 for Linux.

**Comment by suamor** [comment]
> > I have used wine-8.21-tkg-staging download for Ubuntu 22.04 LTS and ModOrganizer 2.5.1 as well as the latest LOOT 0.22.3 work just fine (non-proton wine). I can't check the proton wine tkg on Ubuntu.
> 
> Would you mind sharing how you accomplished this? wine staging tkg doesn't work by running it as a proton version, which is needed when using this repo's method of installing MO2 for Linux. Plus as it is normal wine, how is one supposed to play the games effectively?

I copied wine-8.21-staging-tkg-amd64 into ~/.local/share/Steam/compatibilitytools.d/ because some tools make use of that folder (steam and lutris ignore it unfortunately). You can use WINE variable to define the wine binary and either start mo2 from console or start a wineserver. 

Second part is to define your WINEPREFIX path. It will be updated to wine-tkg, so this is best done with winetricks to create a new profile. I risked the update on my STL prefix (and later recreated it). The main topic you have is to install all dependencies in the prefix which STL or mo2-linux-installer do automatically and both require a proton wine. 

Skyrim itself does not strictly require proton wine, but performance or plugins may profit.

**Comment by cprin21** [comment]
You know, that is 100% beyond what I know how to do. Plus I doubt its ability to properly run games well considering it's not a lutris wine, wine ge, or proton.

**Comment by suamor** [comment]
Skyrim is a special beast, I agree on that. The basic Special Edition runs fine on way older wine releases. When using mo2 to add mods, the virtual drive feature for one need to be working. 

The current situation is only there because of a bug in wine that was not patched inside any of the proton releases and because it apparently was not reported. It's a problem that arised many months ago when changes were done in the framework used by MO2.

My guess on this is that there are currently no games that use that framework and that tools have a very low priority for proton (steam) or lutris. Proton-tkg is the only variant that I read about that may support 2.5. It will only run on Ubuntu 23.10 or others from this autumn with the latest libc and there has been no release builds since months.

**Comment by cprin21** [comment]
https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/proton-arch-nopackage.yml
This version of Proton built with the bleeding edge of Wine as the base works with version 2.5. 
If someone was able to make an update which downloads 2.5 instead of 2.4.4, as well as enables support for 2.5-added games like Starfield, this issue can close.

**Comment by suamor** [comment]
I'm not on arch but I am now able to build on Ubuntu 22.04. 

The staging build (8.0.74x) is not working with 2.5. 

I have to check if there are other configuration options to get a more recent wine included.

**Comment by rockerbacon** [comment]
Since we target stable Proton releases from Steam, this update might be blocked for a while.
I'm open to doing an "unstable" release under a separate branch, but I'd need someone to point me out to some Proton release that currently works (be it TKG, GE or anything else) so we can properly instruct users on how to get things working.

**Comment by suamor** [comment]
One positive update from my side: 2.5.1rc is running in a wine-9.0 / proton environment (tkg). While building of wine is relatively straight forward (you only have to make sure to set the correct configuration options), for proton I have used option "4" since I had previously build problems with other experimental options.

**Comment by connortaumoepeau** [comment]
Is there any progress on 2.5 update? Is it still broken or a new proton build that runs this?

**Comment by suamor** [comment]
https://github.com/ValveSoftware/Proton/releases
Beta releases have been published. 
https://github.com/Kron4ek/Wine-Builds/releases
TKG Wine has meanwhile multiple releases as well.

I still use my own older build. So far I did only occur one issue, but it could be an issue not related to wine-9.0 directly.
I encountered no  issues with MO2 so far.

**Comment by rockerbacon** [comment]
Anyone with patches updating the MO2 download link is free to open a pull request. We can start with an experimental release in anticipation of #582 and move to stable once Proton 9.0 is out of beta.

**Comment by AZCurt** [comment]
Posted Proton GE 9.1 testing in # 582
Cliff Notes version, it all works. including MO2 v2.5.0

https://github.com/rockerbacon/modorganizer2-linux-installer/issues/582

**Comment by lotumusic** [comment]
Also tested on Proton GE 9.1 on the steam deck. Confirmed v2.50 is working, I updated via MO2 itself. Starfield plugins work as they should.

**Comment by tdtooke** [comment]
2.5 works on my setup pretty flawlessly as well.  The only thing I don't like is the loot plugin doesn't display the kinds of things it used to display.  Like if SKSE was found and set up properly, or the reminder to run FNIS or telling you to download the flashing screen fixer if you have skyui.  It definitely does sort the plugins though.  To give me that added feedback I like I installed loot on my game prefix and added it as an executable.  I might actually prefer it that way to the way it comes in 2.5
