### ISSUE TITLE
Add support for skyrimVR

### ISSUE THREAD

**Issue by nuggiz** [rockerbacon/modorganizer2-linux-installer#548]
Hi, thanks for this awesome project. is it possible to add support for SkyrimVR?

xoxo :]

**Comment by NielsRenard** [comment]
I got it working by adding a skyrimvr.sh file to the gamesinfo folder
```
game_steam_subdirectory="SkyrimVR"
game_nexusid="skyrimspecialedition"
game_appid=611670
game_executable="SkyrimVR.exe"
game_protontricks=("xaudio2_7=native")
game_scriptextender_url="https://skse.silverlock.org/beta/sksevr_2_00_12.7z"
game_scriptextender_files=( \
	"sksevr_2_00_12/Data" \
	"sksevr_2_00_12/sksevr_1_4_15.dll" \
	"sksevr_2_00_12/sksevr_loader.exe" \
	"sksevr_2_00_12/sksevr_steam_loader.dll" \
)
```

and adding an entry to steps/select_game.sh

```
selected_game=$( \
	"$dialog" \
		radio \
		450 "$screen_text" \
		"enderal" "Enderal: Forgotten Stories" \
		"enderal_se" "Enderal: Forgotten Stories (Special Edition)" \
		"fallout3" "Fallout 3" \
		"fallout3_goty" "Fallout 3 - Game of the Year Edition" \
		"fallout4" "Fallout 4" \
		"newvegas" "Fallout: New Vegas" \
		"newvegas_ru" "Fallout: New Vegas RU" \
		"morrowind" "Morrowind" \
		"oblivion" "Oblivion" \
		"skyrim" "Skyrim" \
		"skyrimspecialedition" "Skyrim Special Edition" \
		"skyrimvr" "Skyrim VR" \
)
```

not sure if this line is necessary, I just copied it from another one of those files
```
game_protontricks=("xaudio2_7=native")
```


Working like a charm, thanks for this software @rockerbacon

**Comment by abstractionmage** [comment]
Did you manage to get it to work with SKSEVR? If I try to run the sksevr_loader.exe with mods through this mod organizer, I get an error message saying "Couldn't retrieve EXE version information"

**Comment by abstractionmage** [comment]
Ok I fixed it. The error was due to sksevr_loader.exe trying to launch SkyrimVR.exe, which points to the mod organizer instead of the actual game, but fortunately there is a way to tell SKSEVR to look for a differently named SkyrimVR executable, in this case _SkyrimVR.exe.

Step 1: Go to your instance folder. It should be under `~/.local/share/Steam/steamapps/compatdata/611670/pfx/drive_c/users/steamuser/AppData/Local/ModOrganizer/`

Step 2: Navigate to `overwrite/SKSE/`

Step 3: Create a new file here called `SKSE.ini` with the following contents:
```
[Loader]
RuntimeName=_SkyrimVR.exe
```

That's it, now it should work.

---

*(Screenshot of how I edited the file in Kate to make it clear to anybody where it belongs)*

![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/37195767/42883ef1-cbfc-4f49-ab5d-60631393d939)

**Comment by rockerbacon** [comment]
If anyone would like, please feel free to open a PR to merge what was discussed here in the main branch.

The creation of the `overwrite/SKSE/SKSE.ini` file can be done in the workaround step, in the same way that the DXVK memory patch is applied to Skyrim in [workarounds/skyrim.sh](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/workarounds/skyrim.sh).
