### ISSUE TITLE
Dropping Morrowind support in favor of OpenMW

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#552]
[OpenMW](https://openmw.org/) is the optimal way of running Morrowind nowadays and it includes native modding support.

I'd prefer to redirect users to OpenMW instead of giving them an option for a subpar MO2 experience.

**Comment by hazelnot** [comment]
There's disagreement about whether OpenMW is actually the optimal way of running/modding Morrowind. Seems like the modding community went back to the original game because the script extender got some very powerful features that allow mods that simply aren't possible on OpenMW even with the engine being open source.

**Comment by danaYatsuta** [comment]
OpenMW is great, but most of the modding scene is happening on vanilla Morrowind because of MWSE and it looks like it's going to be the case for a while. If Morrowind support were to be dropped, that would be sad

**Comment by rockerbacon** [comment]
I hear your concerns on the necessity of MWSE for some mods. This will not be moving forward.
