### ISSUE TITLE
"No prefix found" message while trying to use install.sh

### ISSUE THREAD

**Issue by indigogal** [rockerbacon/modorganizer2-linux-installer#576]
After running the game for the first time to populate the files and then closing it and running the install.sh file, selecting fallout 4 and continuing the process the next error is shown on the terminal

`INFO: all dependencies met`
`INFO: selected game 'fallout4'`
`INFO: found Steam in '/home/indigo/.local/share/Steam'`
`INFO: game not found in '/home/indigo/.local/share/Steam'`
`INFO: game found in '/mnt/harder-drive/SteamLibrary'`
`INFO: found Steam in '/home/indigo/.var/app/com.valvesoftware.Steam/.local/share/Steam'`
`INFO: user confirmed prefix setup`
`ERROR: no prefix found`

i am fairly new to using bare wine and protontricks as i mainly use bottles, so any help is appreciated, please request any information that may be required to help resolve this issue, which is very likely, user fault.

**Comment by rockerbacon** [comment]
Happens when the user confirms prefix setup without having setup the prefix. Read and follow the instructions presented during the install process.

**Comment by seankimbletaylor** [comment]
> Happens when the user confirms prefix setup without having setup the prefix. Read and follow the instructions presented during the install process.

This happens _after_ following the steps in the prefix setup process. I can confirm a prefix exists in the steam app directory (e.g. for Skyrim `489830`):

```
user@computer: ~/Downloads/mo2installer$ ls ~/.steam/steam/steamapps/compatdata/489830/pfx
dosdevices  drive_c  system.reg  userdef.reg  user.reg
user@computer:~/Downloads/mo2installer$ 
```

But I still see the error:
```
INFO: user confirmed prefix setup
ERROR: no prefix found
```

I'm not sure if the prefix setup process needs to be doing something else or if the user needs to be doing something else. But the setup guide doesn't answer this question.

**Comment by weayer404** [comment]
Although it might be too late to respond now, the issue seems to be that the Protontricks utility is unable to read your game directory, possibly due to dual-boot system configurations. I encountered a similar problem; when I opened Protontricks, instead of displaying a list of games, it threw an error. This can be resolved by granting Protontricks access to global files using Flatseal. For details, refer to BV1CA411r7DT in bilibili :) (a chinese vedio web). After granting the necessary permissions and reinstalling according to the procedure, the issue should be resolved

**Comment by lenny878** [comment]
Might also be a bit late to the party but I have the exact same issue.
PSA: If you have a german market copy of Fallout New Vegas MO2 will (kinda) not work for you on the Steam Deck.

Because if you leave your Fallout New Vegas unpatched (swapping the Fallout.exe to convert the game to the gore/standard variant) you are able to install MO2 through the process but NVSE will not work. 
Replacing the Fallout.exe with the gore patch after install of MO2, will simply result in MO2 not starting up.

And if you patch your Fallout New Vegas before attempting to install MO2, you will simply get the prefix issue you are describing. 
So no install possible under this circumstance.

If anyone has a solution to this please let me know. :D 
For now it's only texture mods for me.

**Comment by ChanceNCounter** [comment]
I'm also getting this. I can confirm MO2 works on my system; it's currently managing a heavily modded FO4 with no trouble. When I try to install it for FO3: GOTY, I get what OP is getting.

Happy to provide whatever logs or specs are relevant.

**Comment by kgagnon** [comment]
> Happens when the user confirms prefix setup without having setup the prefix. Read and follow the instructions presented during the install process.

Well you're just being arrogant for the sake of being arrogant.

The clean prefix steps are brief, simple and easy to follow. If someone have issues is because something is wrong. for Skyrim SE it says to force a specific proton version and launch the game. that's it. Super real fn easy to do and yet it doesn't work.
