### ISSUE TITLE
Update to Proton 9.0

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#582]
Valve has release beta builds of Proton 9.0. We should get ready for the update.

The update process is just a matter of testing the newer version and updating the Proton version recommendations in the installer and documentation.

Testers wanted.

Related to #543 and #528

**Comment by Nyonyix** [comment]
I can help out with this in a week or so, Swapping my GPUs out.

I run proton GE by default which is version 9 at the moment. My games include FO(3, NV, 4) and SSE.

Running FO4 vanilla out of the box, GE 9 seems perfectly fine. I have run into an issue with SSE, My mouse is bound to the upper corner. I am unsure if that a proton or system/install issue.

**Comment by AZCurt** [comment]
Installed MO 2 for use with Skyrim AE with the following. (System specs at the bottom)

GEproton 9.1 (via ProtonUP-QT)  and using the following command input options
WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b"  %command%

Thus far I have no problems interacting with Nexus Mods, including update checking, downloading and installing. 

Tested SSEEditx64 v4.03 with a 527 mod load order with no problems opening, editing and saving mods.

Updated to SSEEdit v 4.04 and loaded, edited and saved mods with no problem.

I have yet to try SSEEdit 4.1.5-experimental.

The bodyslide suite, Textgen64, DynDOLOD64, FNIS for Users v 7.6XXL and WryeBash 311 Stand alone works. Wrye Bash 312.1 does not see the SSE directory.

Creation Kit loaded and rendered. I did not test further at this time, but it is a good start.

As an added benefit, LOOT v 22.3 runs as intended with no problems.

Skyrim loads with Reshade, but I have some mouse issues. As its been a while since I ran SSE it could be the whole Plasma 6 (upgrade?) business with Wayland. More testing on my part there is needed. 

System Specs:

Arch Linux
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-zen1-1-zen
Graphics Version: Wayland
CPU: AMD Ryzen 7 7700X
RAM: 64G
GPU: AMD Radeon RX 7800 XT

**Comment by calvincorrieri** [comment]
Hey idk how this works but I have an OLED steam deck and am willing to test the installer with proton 9

**Comment by CurrentSubset68** [comment]
there is some discussion about proton 9 on this guides comment section that might help
https://www.nexusmods.com/skyrimspecialedition/mods/91500?tab=posts

**Comment by CurrentSubset68** [comment]
using proton-GE 9.4, i have no issues ingame. it also makes the mod 'Desktop splash screen' work properly compared to when running proton 8. the one issue i can see is that proton 9 disables the SKSE console log. no DLL work arounds needed for any mods. not using ENB, but using community shaders. (also there is reports of proton 8 crashing Open Animation Replacer)
Running 1.6.1170.


specs
OS: EndeavourOS Linux x86_64 
Host: MS-7C37 1.0 
Kernel: 6.8.7-zen1-1-zen 
Uptime: 9 hours, 26 mins 
Packages: 1556 (pacman), 68 (flatpak) 
Shell: bash 5.2.26 
Resolution: 2560x1440 
DE: Plasma 6.0.4 
WM: kwin 
Theme: [Plasma], Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
GPU: AMD ATI Radeon RX 6950 XT 
Memory: 13151MiB / 32010MiB

**Comment by tdtooke** [comment]
I'm not 100% sure but I think newer versions of SKSE default to no console.  Could be wrong, could've sworn I read that somewhere.  I can add that I've pretty much never used the recommended version of proton for MO2 not when it recommended 6 and not now.  I've always used the latest GE Proton and I've never had a problem.

**Comment by maxreitner** [comment]
Its here,
https://github.com/ValveSoftware/Proton/releases/tag/proton-9.0-1
