### ISSUE TITLE
zEdit does not work

### ISSUE THREAD

**Issue by catmagi** [rockerbacon/modorganizer2-linux-installer#60]
I'm currently approaching 255 plugins on my skyrim se install and was going to spin up[ zedit](https://github.com/z-edit/zedit) so that I could merge some plugins together so I could fit in a few more key additions when to my horror zEdit would not work in mod organizer. It's made double annoying because it'll work through launching it with wine fine but it won't work with my mod list unless I load it through mod organizer.

anyways here's a log

https://hasteb.in/jiqaguqo.coffeescript

this project is awesome btw, I didn't know about the awesomeness of mod organizer before I saw this project posted on reddit and it's made modding a TON more enjoyable, you really can't beat it.

**Comment by rockerbacon** [comment]
This is known bug in WSL which affects Wine, check #17 for details.

You will need to find a version of zEdit which still uses Electron 4. Checking [their releases](https://github.com/z-edit/zedit) it seems there was an update to Electron 5.0.8 in version 0.6.5, so I'd start trying 0.6.4.

Maybe Wine fixed the bug in its latest version which is why you can get it to work running directly through Wine.

**Comment by catmagi** [comment]
update on this, I used the version that released before the current one and it worked fine. Was able to merge mods and use zEdit modules to run mods like know your enemy.
