### ISSUE TITLE
Installing MO2 for FONV Stops when Downloading Jun2010 Redist

### ISSUE THREAD

**Issue by SomeoneWhoWantsSmthngToWork** [rockerbacon/modorganizer2-linux-installer#609]
I’ve been trying to get this working for a while now but nothing seems to work. When I run the install script and choose Fallout New Vegas, down the line it says that the Jun2010 redistributable does not match. It then tries to download it but it never finishes. Below is a screenshot of it.
![IMG_5957](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/167775329/5669647b-a07c-4e33-a6e1-ba9b21bfabe5)

**Comment by rockerbacon** [comment]
This has been reported in a comment before: https://github.com/rockerbacon/modorganizer2-linux-installer/issues/602#issuecomment-2068145292

From what I can see, it's a Winetricks issue. Winetricks verifies checksums for all files it downloads, and something you're trying to download doesn't match the expected checksum.

Sometimes this is caused by Microsoft updating old files and Winetricks using outdated checksums, but that doesn't seem to be the case. I quickly checked the [holarse-linuxgaming.de mirror](https://files.holarse-linuxgaming.de/mirrors/microsoft/) and it looks like the file in question hasn't been updated since 2021.

Considering the previous commenter "fixed" their issue by essentially re-running the installer, I believe the `holarse-linuxgaming.de` mirror may be experiencing instabilities. Try running the installer again and see how it goes.

You can also manually cache the file by downloading it from the mirror and placing it under `/home/deck/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9`

**Comment by rockerbacon** [comment]
Closing as stale
