### ISSUE TITLE
Doesn't work with Proton-GE

### ISSUE THREAD

**Issue by hawari21** [rockerbacon/modorganizer2-linux-installer#712]
Hello, today i was installing MO2 and its works!, however after i switched to Proton-GE and my launcher is running F4SE_loader instead of MO2 like supposed to, and only working with steam proton version. Is there any way to use Proton-GE? Thank you.

**Comment by ajventer** [comment]
This is due to a missmatch with a proton-GE feature. GE detects when you have F4SE installed and launches it automatically by intercepting the call. 

Ironically this brings the linux behavior inline with windows where a library hook causes F4SE to automatically get triggered when you launch the game.

The following MAY be a viable work-around, it depends whether GE is responding to the loader being present or the library hook.

1) Rename f4se_loader to something else ("real_loader_with_f4se.exe" or something
2) In ModOrganizer - edit your executables to point the f4se option to the new name
