### ISSUE TITLE
MO2 and target game need to be launched using the same version of Wine

### ISSUE THREAD

**Issue by brandonegbert** [rockerbacon/modorganizer2-linux-installer#73]
It's not possible to use one version of Wine/Proton for MO2 and one for the game itself because the game needs to be launched from within MO2 due to it's virtual file system.  If the game is launched outside of MO2 mods don't show up.

Usecase for this would be that some versions of Proton will fix issues in the game but not work for running MO2.  For example, currently a custom TKG Proton build is reported to fix some issues with decals in Fallout 4 but the custom TKG build does not work with MO2 (TKG author says it won't work outside of Steam though I don't know why).

I'm not sure there's anything that can be done about this at the moment since there doesn't seem to be a way to disable VFS for MO2.

**Comment by rockerbacon** [comment]
It's not possible and it's also not advisable. Using a newer version of Wine can make a prefix unusable in older versions.

The best "solution" for this is to search for a MO2 version that the custom build you're trying to use supports. The latest MO2 version (2.2.2.1) seems to only be supported by Valve's Proton 5 because of the update to Visual C++ 2019 but versions 2.2.0 and older have much better support since they still use Visual C++ 2017.
