### ISSUE TITLE
"EnablePostPassShader" not functional in ENB .355

### ISSUE THREAD

**Issue by KorgiSilvercloud** [rockerbacon/modorganizer2-linux-installer#95]
First of all, I would like to take a moment to properly thank you guys for all of the hard work you are doing. I didn't see a discord link, or an area for casual chatter so i will just put that here. I have been modding bethesda games on and off for about 11 years now, and the inability to properly do so on linux is the 1 thing that always had me eventually wandering back to windows...with this project though, it would seem i can finally put my windows partition to rest and not have to constantly dual boot...so for that I thank you immensely! 

I have noticed 1 small issue in Fallout 4, when playing with enb binary .355 (havent tried any others yet) and Photorealistic Commonwealth ENB. When loading into the game, the entire screen is just black, and stays that way until you open the enb settings page and turn off "EnablePostPassShader". Doing so allows the enb to function as intended for the most part, just without support for that extra shader it would seem.

**Comment by rockerbacon** [comment]
Readme updated to contain the new information. Issue will remain open until a fix can be found.

**Comment by rockerbacon** [comment]
From what I gathered testing on Skyrim Special Edition, ENB is prone to generating broken shaders which makes DXVK's life a lot more difficult. More information can be found in [this DXVK issue](https://github.com/doitsujin/dxvk/issues/865).

Post and pre pass shaders can also include custom shaders, not written by the ENB developer himself, and that adds to the problem. The problem here might be just a single custom shader and not the default ENB shaders. I'd appreciate if anyone could confirm if other ENB presets suffer from the same issue.

**Comment by Continous** [comment]
This seems to be a largely driver issue with NVidia's proprietary Linux driver. It will likely be fixed in a later driver, or/and can be fixed by rolling drivers back.
